/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Applications
         * @description List recent application records, newest first.
         *
         *     Args:
         *         service: Shared application service from the app state.
         *         limit: Maximum number of records to return.
         *
         *     Returns:
         *         Application history rows (audit metadata + snapshot hashes only).
         */
        get: operations["list_applications_api_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Attention
         * @description Six-bucket attention report — the digest footer's data over the wire.
         *
         *     Args:
         *         workflow: Shared workflow service from the app state.
         *         store: Shared job store (pipeline-health read).
         *
         *     Returns:
         *         Three workflow buckets plus three pipeline-health buckets, both
         *         with store-default thresholds.
         */
        get: operations["attention_api_attention_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Companies
         * @description List tracked companies, slug-ascending.
         *
         *     Args:
         *         store: Shared job store from the app state.
         *         vendor: Optional ATS vendor filter.
         *         include_removed: Whether soft-removed rows are included.
         *
         *     Returns:
         *         Company rows with vendor, failure count, and the derived removed flag.
         */
        get: operations["list_companies_api_companies_get"];
        put?: never;
        /**
         * Add Company
         * @description Track a company with a pinned vendor (upsert; never re-probed).
         *
         *     The upsert's ON CONFLICT path also restores a soft-removed slug: the new
         *     vendor overwrites the removal sentinel.
         *
         *     Args:
         *         body: Slug and pinned ATS vendor.
         *         store: Shared job store from the app state.
         *
         *     Returns:
         *         The written row (vendor pinned, failure counter reset to zero).
         */
        post: operations["add_company_api_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Add Companies
         * @description Upsert many companies at once, skipping slugs that are already active.
         *
         *     Payload duplicates collapse to their first occurrence. Slugs tracked and
         *     not removed are skipped; everything else — new or soft-removed — goes
         *     through the same upsert path as the single POST, so a removed company in
         *     the payload is restored. Bulk rows write ``ats_override=False``
         *     (mirroring ``bootstrap-companies``) so bulk-added vendors stay
         *     re-probeable.
         *
         *     Args:
         *         body: Bulk rows (slug + vendor each).
         *         store: Shared job store from the app state.
         *
         *     Returns:
         *         Count of rows upserted (new plus restored).
         */
        post: operations["bulk_add_companies_api_companies_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Probe Companies
         * @description Resolve each pasted entry's ATS vendor without writing anything.
         *
         *     Entries are normalized to candidate slugs (lowercase trim; vendor board
         *     URLs reduce to their slug), then probed under a per-request concurrency
         *     bound of 5. One entry's failure never aborts the batch.
         *
         *     Args:
         *         body: Pasted entries (1..200).
         *         probe: Injected per-slug vendor probe from the cli assembly.
         *
         *     Returns:
         *         Per-entry results in request order.
         */
        post: operations["probe_companies_api_companies_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Company
         * @description Stop tracking a company (soft remove via the vendor sentinel).
         *
         *     The path slug is normalized (trim + lowercase) before the store call,
         *     matching the write endpoints' slug handling.
         *
         *     Args:
         *         slug: Company board slug.
         *         store: Shared job store from the app state.
         *
         *     Returns:
         *         Acknowledgement.
         *
         *     Raises:
         *         ApiError: 422 for text outside the slug charset; 404 when the slug
         *             is unknown or already removed.
         */
        delete: operations["remove_company_api_companies__slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Report process liveness and database reachability.
         *
         *     Args:
         *         store: Shared job store from the app state.
         *
         *     Returns:
         *         200 ``{"status": "ok", "db": "ok"}`` when a cheap store read
         *         succeeds, else 503 with a degraded body.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Insights Overview
         * @description Aggregate insights: totals, distributions, daily series, app stats.
         *
         *     Totals and distributions are all-time; the daily series and the
         *     application stats cover the requested window.
         *
         *     Args:
         *         service: Shared insights service from the app state.
         *         window: Window in days (1..365) for the daily series and app stats.
         *
         *     Returns:
         *         Composed overview response.
         */
        get: operations["insights_overview_api_insights_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List jobs for one tab with optional filters, fold, sort, pagination.
         *
         *     ``tab_counts`` apply ALL request filters (statuses, search, freshness,
         *     require_verdict), so sidebar/global counts should come from requests
         *     WITHOUT ``statuses``/``require_verdict`` narrowing.
         *
         *     Args:
         *         params: Validated query parameters (plan A4 contract).
         *         service: Shared jobs view service from the app state.
         *
         *     Returns:
         *         Jobs page: ``jobs`` (the view rows), true ``total``, ``tab_counts``.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/bulk/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Transition
         * @description Transition multiple jobs with twin-cluster cascade.
         *
         *     Args:
         *         body: Requested (id, to) pairs and the force flag.
         *         service: Shared workflow service from the app state.
         *
         *     Returns:
         *         Outcome summary: succeeded, skipped, failed items, cascaded count.
         *
         *     Raises:
         *         ApiError: 422 when a job id is not numeric.
         */
        post: operations["bulk_transition_api_jobs_bulk_transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Detail
         * @description Aggregate the full detail view for one job.
         *
         *     Args:
         *         job_id: Store-assigned job identity (numeric).
         *         service: Shared jobs view service from the app state.
         *
         *     Returns:
         *         Job, evaluation blocks, status + history + notes, twins, interview
         *         rounds, and application snapshot refs.
         *
         *     Raises:
         *         HTTPException: 404 (shared error shape) when the job is unknown.
         */
        get: operations["get_job_detail_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply To Job
         * @description Record an application with resume snapshots and audit fields.
         *
         *     Mirrors the CLI apply command: master resume read from settings,
         *     Stage B snapshot fields captured via the shared service helper, and the
         *     no-op parity result when the job was already applied.
         *
         *     Args:
         *         job_id: Store-assigned job identity.
         *         request: Current request (carries the app settings).
         *         form: Parsed multipart upload + form fields.
         *         service: Shared application service from the app state.
         *         store: Shared job store (existence check only).
         *
         *     Returns:
         *         ``applied`` flag plus the reapply notice when one applies.
         *
         *     Raises:
         *         ApiError: 404 unknown job; 422 non-UTF-8 upload; 409 with code
         *             ``illegal_transition`` when the job is in a terminal status.
         */
        post: operations["apply_to_job_api_jobs__job_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/followup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Followup
         * @description Set the next follow-up time for a job.
         *
         *     Args:
         *         job_id: Store-assigned job identity.
         *         body: ISO datetime of the next follow-up.
         *         service: Shared workflow service from the app state.
         *
         *     Returns:
         *         Acknowledgement.
         *
         *     Raises:
         *         ApiError: 404 when the job has no status row.
         */
        post: operations["set_followup_api_jobs__job_id__followup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Interviews
         * @description List a job's interview rounds, ascending by round index.
         *
         *     Args:
         *         job_id: Store-assigned job identity.
         *         service: Shared workflow service from the app state.
         *
         *     Returns:
         *         Interview rounds of the job.
         */
        get: operations["list_interviews_api_jobs__job_id__interviews_get"];
        put?: never;
        /**
         * Add Interview
         * @description Add an interview round (auto-transitions applied -> interviewing).
         *
         *     Args:
         *         job_id: Store-assigned job identity.
         *         body: Round label and optional scheduled time.
         *         service: Shared workflow service from the app state.
         *         store: Shared job store from the app state.
         *
         *     Returns:
         *         The newly created round.
         *
         *     Raises:
         *         ApiError: 404 when the job has no status row.
         */
        post: operations["add_interview_api_jobs__job_id__interviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/interviews/{round_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Complete Interview
         * @description Complete the indexed interview round, attaching optional notes.
         *
         *     Args:
         *         job_id: Store-assigned job identity.
         *         round_index: Round index to complete.
         *         body: Optional notes.
         *         service: Shared workflow service from the app state.
         *
         *     Returns:
         *         The completed round.
         *
         *     Raises:
         *         ApiError: 404 when no open round exists at that index.
         */
        patch: operations["complete_interview_api_jobs__job_id__interviews__round_index__patch"];
        trace?: never;
    };
    "/api/jobs/{job_id}/jd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Paste Jd
         * @description Store manually pasted JD text and report the assessed quality.
         *
         *     Resolves the job's platform + canonical_id, delegates to the store's
         *     ``enrich_paste``, then re-reads the job for its stored quality band.
         *
         *     Args:
         *         job_id: Store-assigned job identity.
         *         body: Pasted JD text (non-blank).
         *         store: Shared job store from the app state.
         *
         *     Returns:
         *         Job id and its stored assessed JD quality.
         *
         *     Raises:
         *         ApiError: 404 when the job is unknown.
         */
        post: operations["paste_jd_api_jobs__job_id__jd_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Note
         * @description Append a note to a job (resets its ghost clock).
         *
         *     Args:
         *         job_id: Store-assigned job identity.
         *         body: Note text (non-blank).
         *         service: Shared workflow service from the app state.
         *
         *     Returns:
         *         Acknowledgement.
         *
         *     Raises:
         *         ApiError: 404 when the job has no status row.
         */
        post: operations["add_note_api_jobs__job_id__note_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Job
         * @description Restore a ghosted/archived job to its last non-terminal status.
         *
         *     The restore target comes from the job's status history (domain
         *     ``pick_restore_target``) — never recomputed client-side.
         *
         *     Args:
         *         job_id: Store-assigned job identity.
         *         service: Shared workflow service from the app state.
         *         store: Shared job store from the app state.
         *
         *     Returns:
         *         Job id and the status the job was restored to.
         *
         *     Raises:
         *         ApiError: 404 when the job has no status row; 409 with code
         *             ``not_restorable`` when the job is not ghosted or archived.
         */
        post: operations["restore_job_api_jobs__job_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transition Job
         * @description Transition a single job, optionally appending a note.
         *
         *     Args:
         *         job_id: Store-assigned job identity.
         *         body: Target status, optional note, force flag.
         *         service: Shared workflow service from the app state.
         *
         *     Returns:
         *         The job's resulting status.
         *
         *     Raises:
         *         ApiError: 404 when the job has no status row; 409 with code
         *             ``illegal_transition`` when the transition graph forbids it.
         */
        post: operations["transition_job_api_jobs__job_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performance/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Funnel
         * @description Evaluation funnel snapshots from pipeline runs.
         *
         *     Args:
         *         service: Shared performance service.
         *         window: Window in days (1..365).
         *
         *     Returns:
         *         Funnel response.
         */
        get: operations["funnel_api_performance_funnel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performance/llm-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Stats
         * @description Daily LLM latency percentiles and token averages.
         *
         *     Args:
         *         service: Shared performance service.
         *         window: Window in days (1..365).
         *
         *     Returns:
         *         LLM daily stats response.
         */
        get: operations["llm_stats_api_performance_llm_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performance/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Performance Overview
         * @description Aggregate performance metrics with period-over-period deltas.
         *
         *     Args:
         *         service: Shared performance service.
         *         window: Window in days (1..365).
         *
         *     Returns:
         *         Performance overview response.
         */
        get: operations["performance_overview_api_performance_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performance/step-timings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Step Timings
         * @description Step timing series within the window, optionally filtered.
         *
         *     Args:
         *         service: Shared performance service.
         *         window: Window in days (1..365).
         *         step_type: Optional filter on step_type.
         *
         *     Returns:
         *         Step timings response.
         */
        get: operations["step_timings_api_performance_step_timings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List pipeline runs, newest first, with the all-time total.
         *
         *     Args:
         *         store: Shared job store.
         *         limit: Max runs returned.
         *         offset: Runs to skip.
         *
         *     Returns:
         *         Runs window plus the total.
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Runs
         * @description Return all currently active (in-progress) runs.
         *
         *     Args:
         *         run_manager: Shared run manager.
         *
         *     Returns:
         *         Active runs keyed under ``runs``.
         */
        get: operations["get_active_runs_api_runs_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Evaluate
         * @description Trigger a background evaluate run.
         *
         *     Args:
         *         body: Request body with stage, corpus, limit.
         *         run_manager: Shared run manager.
         *
         *     Returns:
         *         The new run's identity and initial status.
         *
         *     Raises:
         *         ApiError: 409 when an evaluate is already running.
         */
        post: operations["trigger_evaluate_api_runs_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Scan
         * @description Trigger a background scan run.
         *
         *     Args:
         *         body: Request body with source name.
         *         run_manager: Shared run manager.
         *         request: Current request (for context access).
         *
         *     Returns:
         *         The new run's identity and initial status.
         *
         *     Raises:
         *         ApiError: 409 when a scan is already running, 400 for unknown source.
         */
        post: operations["trigger_scan_api_runs_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Load one pipeline run by identity.
         *
         *     Args:
         *         run_id: Run identity.
         *         store: Shared job store.
         *
         *     Returns:
         *         The run's counters-only summary.
         *
         *     Raises:
         *         ApiError: 404 when the run is unknown.
         */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Progress
         * @description Stream progress events for a run as Server-Sent Events.
         *
         *     Args:
         *         run_id: Run identity to stream.
         *         run_manager: Shared run manager.
         *         store: Shared job store for checking finished runs.
         *
         *     Returns:
         *         SSE streaming response.
         *
         *     Raises:
         *         ApiError: 404 when the run is unknown.
         */
        get: operations["stream_progress_api_runs__run_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApplicationDetail
         * @description Application audit refs: snapshot hashes only, never contents.
         */
        ApplicationDetail: {
            /** Application Method */
            application_method: string | null;
            /**
             * Applied At
             * Format: date-time
             */
            applied_at: string;
            /** Master Resume Hash */
            master_resume_hash: string | null;
            /** Tailored Resume Hash */
            tailored_resume_hash: string | null;
        };
        /**
         * ApplicationRow
         * @description One applications-history row: audit metadata + snapshot hashes only.
         */
        ApplicationRow: {
            /** Application Method */
            application_method: string | null;
            /**
             * Applied At
             * Format: date-time
             */
            applied_at: string;
            /** Job Id */
            job_id: string;
            /** Master Resume Hash */
            master_resume_hash: string | null;
            /** Notes */
            notes: string | null;
            /** Tailored Resume Hash */
            tailored_resume_hash: string | null;
        };
        /**
         * ApplicationStatsBlock
         * @description Windowed application stats including the by-resume table.
         *
         *     ``by_resume`` is empty (never null) when no application falls inside
         *     the window.
         */
        ApplicationStatsBlock: {
            /** Applied Count */
            applied_count: number;
            /** By Resume */
            by_resume: {
                [key: string]: components["schemas"]["ResumeVariantStatsRow"];
            };
            /** Interview Count */
            interview_count: number;
            /** Median Days To Response */
            median_days_to_response: number | null;
            /** Offer Count */
            offer_count: number;
            /** Rejection Count */
            rejection_count: number;
            /** Response Count */
            response_count: number;
        };
        /**
         * ApplicationsListResponse
         * @description ``GET /api/applications`` response.
         */
        ApplicationsListResponse: {
            /** Applications */
            applications: components["schemas"]["ApplicationRow"][];
        };
        /**
         * ApplyResponse
         * @description ``POST /api/jobs/{id}/apply`` response.
         *
         *     ``applied`` is False for the no-op parity case (already applied);
         *     ``reapply_notice`` is set only on a new apply with a same-company
         *     active application.
         */
        ApplyResponse: {
            /** Applied */
            applied: boolean;
            /** Reapply Notice */
            reapply_notice: string | null;
        };
        /**
         * AttentionResponse
         * @description ``GET /api/attention``: the digest footer's six buckets.
         *
         *     Three workflow buckets from ``workflow_attention()`` plus three
         *     pipeline-health buckets from ``needs_attention()``, both with
         *     store-default thresholds — the same two calls the digest footer makes.
         */
        AttentionResponse: {
            /** Enrich Errors */
            enrich_errors: components["schemas"]["PipelineAttentionEntry"][];
            /** Follow Up Today */
            follow_up_today: components["schemas"]["WorkflowAttentionEntry"][];
            /** Going Ghosted */
            going_ghosted: components["schemas"]["WorkflowAttentionEntry"][];
            /** Interview Prep */
            interview_prep: components["schemas"]["WorkflowAttentionEntry"][];
            /** Low Quality Scored */
            low_quality_scored: components["schemas"]["PipelineAttentionEntry"][];
            /** Stuck Scoring */
            stuck_scoring: components["schemas"]["PipelineAttentionEntry"][];
        };
        /** Body_apply_to_job_api_jobs__job_id__apply_post */
        Body_apply_to_job_api_jobs__job_id__apply_post: {
            /** Cover Letter */
            cover_letter?: string | null;
            /** Method */
            method?: string | null;
            /** Notes */
            notes?: string | null;
            /** Tailored */
            tailored?: string | null;
            /** Variant */
            variant?: string | null;
        };
        /**
         * BulkCompanyRow
         * @description One company of a bulk-insert request.
         */
        BulkCompanyRow: {
            /** Slug */
            slug: string;
            /**
             * Vendor
             * @enum {string}
             */
            vendor: "greenhouse" | "ashby" | "lever";
        };
        /**
         * BulkFailedItem
         * @description One failed transition of a bulk response.
         */
        BulkFailedItem: {
            /** Error */
            error: string;
            /** Id */
            id: string;
        };
        /**
         * BulkInsertResponse
         * @description Bulk outcome: rows upserted (new + restored; active slugs skipped).
         */
        BulkInsertResponse: {
            /** Inserted */
            inserted: number;
        };
        /**
         * BulkTransitionBody
         * @description ``POST /api/jobs/bulk/transition`` request body.
         */
        BulkTransitionBody: {
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Items */
            items: components["schemas"]["BulkTransitionItem"][];
        };
        /**
         * BulkTransitionItem
         * @description One requested transition of a bulk request.
         */
        BulkTransitionItem: {
            /** Id */
            id: string;
            /**
             * To
             * @enum {string}
             */
            to: "new" | "scored" | "shortlisted" | "awaiting_referral" | "applied" | "interviewing" | "offer" | "rejected" | "ghosted" | "archived" | "ignored";
        };
        /**
         * BulkTransitionResponse
         * @description Bulk-transition outcome summary (cascaded = twin transitions).
         */
        BulkTransitionResponse: {
            /** Cascaded */
            cascaded: number;
            /** Failed */
            failed: components["schemas"]["BulkFailedItem"][];
            /** Skipped */
            skipped: number;
            /** Succeeded */
            succeeded: number;
        };
        /**
         * CompaniesBulkBody
         * @description ``POST /api/companies/bulk`` request body.
         */
        CompaniesBulkBody: {
            /** Rows */
            rows: components["schemas"]["BulkCompanyRow"][];
        };
        /**
         * CompaniesListResponse
         * @description ``GET /api/companies`` response.
         */
        CompaniesListResponse: {
            /** Companies */
            companies: components["schemas"]["CompanyOut"][];
        };
        /**
         * CompanyAddBody
         * @description ``POST /api/companies`` request body (the vendor is pinned).
         */
        CompanyAddBody: {
            /** Slug */
            slug: string;
            /**
             * Vendor
             * @enum {string}
             */
            vendor: "greenhouse" | "ashby" | "lever";
        };
        /**
         * CompanyOut
         * @description One tracked company row of the wire contract.
         */
        CompanyOut: {
            /** Consecutive Discover Failures */
            consecutive_discover_failures: number;
            /** Removed */
            removed: boolean;
            /** Slug */
            slug: string;
            /** Vendor */
            vendor: string | null;
        };
        /**
         * EvaluationDetail
         * @description Evaluation section of the detail response (stages optional).
         *
         *     ``stage_b_status`` is the raw pipeline status (the same store column the
         *     list rows carry), set even when ``stage_b`` is None — below-threshold
         *     rows have no Stage B blocks but still need their derived display state.
         */
        EvaluationDetail: {
            stage_a: components["schemas"]["StageADetail"] | null;
            stage_b: components["schemas"]["StageBDetail"] | null;
            /** Stage B Status */
            stage_b_status: string | null;
        };
        /**
         * FollowupBody
         * @description ``POST /api/jobs/{id}/followup`` request body (ISO datetime).
         */
        FollowupBody: {
            /**
             * At
             * Format: date-time
             * @description Follow-up time; must carry a UTC offset (naive -> 422).
             */
            at: string;
        };
        /**
         * FunnelResponse
         * @description ``GET /performance/funnel`` response.
         */
        FunnelResponse: {
            /** Funnel */
            funnel: components["schemas"]["FunnelRow"][];
        };
        /**
         * FunnelRow
         * @description One funnel snapshot for a pipeline run.
         */
        FunnelRow: {
            /** After Filter */
            after_filter: number;
            /** After Gate */
            after_gate: number;
            /** Run Id */
            run_id: string;
            /** Scored */
            scored: number;
            /** Total Candidates */
            total_candidates: number;
        };
        /**
         * GapDetail
         * @description One missing/weak requirement with severity and mitigation.
         */
        GapDetail: {
            /** Mitigation */
            mitigation: string;
            /** Requirement */
            requirement: string;
            /** Severity */
            severity: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InsightsDayEntry
         * @description One UTC day of the windowed series (only days having data appear).
         */
        InsightsDayEntry: {
            /** Applied */
            applied: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Discovered */
            discovered: number;
            /** Evaluated */
            evaluated: number;
        };
        /**
         * InsightsOverviewResponse
         * @description ``GET /api/insights/overview`` response.
         *
         *     Totals and distributions are all-time; ``daily`` and ``applications``
         *     cover the requested window. ``verdict_distribution`` includes the derived
         *     ``below_threshold`` bucket (triage grouping); both distributions carry
         *     only nonzero buckets.
         */
        InsightsOverviewResponse: {
            applications: components["schemas"]["ApplicationStatsBlock"];
            /** Daily */
            daily: components["schemas"]["InsightsDayEntry"][];
            /** Status Distribution */
            status_distribution: {
                [key: string]: number;
            };
            totals: components["schemas"]["InsightsTotals"];
            /** Verdict Distribution */
            verdict_distribution: {
                [key: string]: number;
            };
            /** Window Days */
            window_days: number;
        };
        /**
         * InsightsTotals
         * @description All-time funnel totals: discovered, gate-passed, evaluated, applied.
         *
         *     ``ml_gate_passed`` counts gate survivors (``ml_gate_result = 'pass'``) —
         *     the funnel-stage semantic, not gate failures; jobs never gated count
         *     toward neither.
         */
        InsightsTotals: {
            /** Applied */
            applied: number;
            /** Evaluated */
            evaluated: number;
            /** Jobs */
            jobs: number;
            /** Ml Gate Passed */
            ml_gate_passed: number;
        };
        /**
         * InterviewAddBody
         * @description ``POST /api/jobs/{id}/interviews`` request body.
         */
        InterviewAddBody: {
            /** Label */
            label: string;
            /**
             * Scheduled At
             * @description Interview time; must carry a UTC offset (naive -> 422).
             */
            scheduled_at?: string | null;
        };
        /**
         * InterviewCompleteBody
         * @description ``PATCH /api/jobs/{id}/interviews/{index}`` request body.
         */
        InterviewCompleteBody: {
            /** Notes */
            notes?: string | null;
        };
        /**
         * InterviewRoundDetail
         * @description One interview round of the detail job.
         */
        InterviewRoundDetail: {
            /** Completed At */
            completed_at: string | null;
            /** Label */
            label: string;
            /** Notes */
            notes: string | null;
            /** Round Index */
            round_index: number;
            /** Scheduled At */
            scheduled_at: string | null;
        };
        /**
         * InterviewsListResponse
         * @description ``GET /api/jobs/{id}/interviews`` response.
         */
        InterviewsListResponse: {
            /** Interviews */
            interviews: components["schemas"]["InterviewRoundDetail"][];
        };
        /**
         * JdPasteBody
         * @description ``POST /api/jobs/{id}/jd`` request body.
         */
        JdPasteBody: {
            /** Text */
            text: string;
        };
        /**
         * JdPasteResponse
         * @description JD paste response: the job's stored assessed quality band.
         */
        JdPasteResponse: {
            /** Jd Quality */
            jd_quality: string | null;
            /** Job Id */
            job_id: string;
        };
        /**
         * JobDetailJob
         * @description The detail job record (full posting incl. JD text).
         */
        JobDetailJob: {
            /** Canonical Id */
            canonical_id: string;
            /** Closed At */
            closed_at: string | null;
            /** Company */
            company: string;
            /**
             * Discovered At
             * Format: date-time
             */
            discovered_at: string;
            /** Id */
            id: string;
            /** Jd Quality */
            jd_quality: string | null;
            /** Jd Text */
            jd_text: string | null;
            /** Location */
            location: string;
            /** Platform */
            platform: string;
            /** Posted At */
            posted_at: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /**
         * JobDetailResponse
         * @description ``GET /api/jobs/{id}`` response.
         */
        JobDetailResponse: {
            application: components["schemas"]["ApplicationDetail"] | null;
            evaluation: components["schemas"]["EvaluationDetail"];
            /** Interviews */
            interviews: components["schemas"]["InterviewRoundDetail"][];
            job: components["schemas"]["JobDetailJob"];
            status: components["schemas"]["StatusDetail"];
            /** Twins */
            twins: components["schemas"]["TwinDetail"][];
        };
        /**
         * JobSummary
         * @description One jobs-list row (the DTO form of ``JobsViewRow``).
         */
        JobSummary: {
            /** Closed At */
            closed_at: string | null;
            /** Company */
            company: string;
            /** Company Norm */
            company_norm: string | null;
            /**
             * Discovered At
             * Format: date-time
             */
            discovered_at: string;
            /** Id */
            id: string;
            /** Jd Quality */
            jd_quality: string | null;
            /** Platform */
            platform: string;
            /** Posted At */
            posted_at: string | null;
            /** Stage A Score */
            stage_a_score: number | null;
            /** Stage B Fit Score */
            stage_b_fit_score: number | null;
            /** Stage B Status */
            stage_b_status: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Title Norm */
            title_norm: string | null;
            /** Url */
            url: string;
            /** Verdict */
            verdict: string | null;
        };
        /**
         * JobsListResponse
         * @description ``GET /api/jobs`` response: rows, true total, SQL tab counts.
         */
        JobsListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobSummary"][];
            /** Tab Counts */
            tab_counts: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /**
         * LLMDailyStatsRow
         * @description One day of LLM stats.
         */
        LLMDailyStatsRow: {
            /** Avg Input Tokens */
            avg_input_tokens: number;
            /** Avg Output Tokens */
            avg_output_tokens: number;
            /** Day */
            day: string;
            /** P50 Latency Ms */
            p50_latency_ms: number;
            /** P95 Latency Ms */
            p95_latency_ms: number;
        };
        /**
         * LLMStatsResponse
         * @description ``GET /performance/llm-stats`` response.
         */
        LLMStatsResponse: {
            /** Stats */
            stats: components["schemas"]["LLMDailyStatsRow"][];
        };
        /**
         * NoteBody
         * @description ``POST /api/jobs/{id}/note`` request body.
         */
        NoteBody: {
            /** Text */
            text: string;
        };
        /**
         * OkResponse
         * @description Generic acknowledgement for side-effect-only routes.
         */
        OkResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /**
         * PerformanceOverviewResponse
         * @description ``GET /performance/overview`` response.
         */
        PerformanceOverviewResponse: {
            /** Avg Eval Duration Ms */
            avg_eval_duration_ms: number;
            /** Avg Scan Duration Ms */
            avg_scan_duration_ms: number;
            /** Cost Delta */
            cost_delta: number | null;
            /** Error Rate */
            error_rate: number;
            /** Error Rate Delta */
            error_rate_delta: number | null;
            /** Eval Duration Delta */
            eval_duration_delta: number | null;
            /** Scan Duration Delta */
            scan_duration_delta: number | null;
            /** Total Llm Cost Usd */
            total_llm_cost_usd: number;
        };
        /**
         * PipelineAttentionEntry
         * @description One pipeline-health row (enrich error, low quality, stuck scoring).
         */
        PipelineAttentionEntry: {
            /** Category */
            category: string;
            /** Company */
            company: string;
            /** Detail */
            detail: string;
            /** Job Id */
            job_id: string;
            /** Title */
            title: string;
        };
        /**
         * ProbeBody
         * @description ``POST /api/companies/probe`` request body (1..200 entries).
         */
        ProbeBody: {
            /** Entries */
            entries: string[];
        };
        /**
         * ProbeEntryResult
         * @description Per-entry probe outcome.
         *
         *     A definitive all-vendor miss is ``vendor=None, error=None``; a
         *     normalization or transport failure carries ``error`` instead.
         */
        ProbeEntryResult: {
            /** Error */
            error: string | null;
            /** Input */
            input: string;
            /** Slug */
            slug: string | null;
            /** Vendor */
            vendor: string | null;
        };
        /**
         * ProbeResponse
         * @description ``POST /api/companies/probe`` response, in request order.
         */
        ProbeResponse: {
            /** Results */
            results: components["schemas"]["ProbeEntryResult"][];
        };
        /**
         * RestoreResponse
         * @description ``POST /api/jobs/{id}/restore`` response: where the job landed.
         */
        RestoreResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /**
         * ResumeHooksDetail
         * @description The three resume-hook blocks of the Stage B output.
         */
        ResumeHooksDetail: {
            /** Avoid Mentioning */
            avoid_mentioning: string[];
            /** Lead With */
            lead_with: string;
            /** Supporting */
            supporting: string[];
        };
        /**
         * ResumeVariantStatsRow
         * @description Per-resume-variant application outcomes.
         */
        ResumeVariantStatsRow: {
            /** Interviews */
            interviews: number;
            /** Offers */
            offers: number;
            /** Rejections */
            rejections: number;
            /** Responses */
            responses: number;
            /** Sent */
            sent: number;
        };
        /**
         * RunSummary
         * @description One pipeline run's identity and counters.
         *
         *     Counters only — ``dry_run_preview`` never rides along on the wire.
         */
        RunSummary: {
            /** Errors */
            errors: number;
            /** Finished At */
            finished_at: string | null;
            /** Jobs Discovered */
            jobs_discovered: number;
            /** Jobs Filtered */
            jobs_filtered: number;
            /** Jobs Inserted */
            jobs_inserted: number;
            /** Jobs Ml Gated */
            jobs_ml_gated: number;
            /** Jobs Scored */
            jobs_scored: number;
            /** Jobs Updated */
            jobs_updated: number;
            /** Run Id */
            run_id: string;
            /** Source */
            source: string;
            /** Stage A Scored */
            stage_a_scored: number;
            /** Stage B Scored */
            stage_b_scored: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Total Llm Cost Usd */
            total_llm_cost_usd: number;
        };
        /**
         * RunsListResponse
         * @description ``GET /api/runs`` response: the requested window plus the total.
         */
        RunsListResponse: {
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
            /** Total */
            total: number;
        };
        /**
         * StageADetail
         * @description Stage A summary: fast score plus its one-line rationale.
         */
        StageADetail: {
            /** One Line */
            one_line: string;
            /** Score */
            score: number;
        };
        /**
         * StageBDetail
         * @description Stage B blocks: verdict, JD summary, fit analysis, resume hooks.
         *
         *     Display DTO — it must never 500 on real-data nulls. Stage B rows in the
         *     live corpus can carry a NULL/absent JD summary or fit score (the verdict-
         *     independent fallback also fills here), so ``jd_summary`` and ``fit_score``
         *     are nullable and the list fields default to empty. ``verdict`` stays a
         *     plain string ("" when unscored, which the pill reads). ``hooks`` keeps a
         *     non-optional empty default so both mapper paths and the frontend never
         *     have to special-case its absence.
         */
        StageBDetail: {
            /** Fit Score */
            fit_score?: number | null;
            /** Gaps */
            gaps?: components["schemas"]["GapDetail"][];
            hooks?: components["schemas"]["ResumeHooksDetail"];
            /** Jd Summary */
            jd_summary?: string | null;
            /** Strengths */
            strengths?: components["schemas"]["StrengthDetail"][];
            /** Verdict */
            verdict: string;
        };
        /**
         * StatusDetail
         * @description Workflow section: current status, notes, follow-up, history.
         */
        StatusDetail: {
            /** History */
            history: string[];
            /** Next Followup At */
            next_followup_at: string | null;
            /** Notes */
            notes: string | null;
            /** Resume Variant */
            resume_variant: string | null;
            /** Status */
            status: string | null;
        };
        /**
         * StepTimingRow
         * @description One step timing row for the series endpoint.
         */
        StepTimingRow: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Is Error */
            is_error: boolean;
            /** Run Id */
            run_id: string;
            /** Step Name */
            step_name: string;
            /** Step Type */
            step_type: string;
        };
        /**
         * StepTimingsResponse
         * @description ``GET /performance/step-timings`` response.
         */
        StepTimingsResponse: {
            /** Timings */
            timings: components["schemas"]["StepTimingRow"][];
        };
        /**
         * StrengthDetail
         * @description One matched requirement with its resume evidence.
         */
        StrengthDetail: {
            /** Evidence */
            evidence: string;
            /** Requirement */
            requirement: string;
        };
        /**
         * TransitionBody
         * @description ``POST /api/jobs/{id}/transition`` request body.
         */
        TransitionBody: {
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Note */
            note?: string | null;
            /**
             * To
             * @enum {string}
             */
            to: "new" | "scored" | "shortlisted" | "awaiting_referral" | "applied" | "interviewing" | "offer" | "rejected" | "ghosted" | "archived" | "ignored";
        };
        /**
         * TransitionResponse
         * @description Single-transition response: the job's resulting status.
         */
        TransitionResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /**
         * TriggerEvaluateRequest
         * @description POST /api/runs/evaluate body.
         */
        TriggerEvaluateRequest: {
            /**
             * Corpus
             * @default unrated
             */
            corpus: string;
            /** Limit */
            limit?: number | null;
            /**
             * Stage
             * @default both
             * @enum {string}
             */
            stage: "a" | "b" | "both";
        };
        /**
         * TriggerScanRequest
         * @description POST /api/runs/scan body.
         */
        TriggerScanRequest: {
            /**
             * Source
             * @default mock
             */
            source: string;
        };
        /**
         * TwinDetail
         * @description One twin posting (same company_norm + title_norm) of the detail job.
         */
        TwinDetail: {
            /** Job Id */
            job_id: string;
            /** Platform */
            platform: string;
            /** Status */
            status: string;
            /** Url */
            url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkflowAttentionEntry
         * @description One workflow attention row (follow-up, interview prep, ghosting).
         */
        WorkflowAttentionEntry: {
            /** Company */
            company: string;
            /** Days Since */
            days_since: number;
            /** Job Id */
            job_id: string;
            /**
             * Last Status Change At
             * Format: date-time
             */
            last_status_change_at: string;
            /** Next Followup At */
            next_followup_at: string | null;
            /** Notes */
            notes: string | null;
            /** Reason */
            reason: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /**
         * _TriggerResponse
         * @description Response body for a successfully triggered run.
         */
        _TriggerResponse: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @default running
             */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_applications_api_applications_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attention_api_attention_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttentionResponse"];
                };
            };
        };
    };
    list_companies_api_companies_get: {
        parameters: {
            query?: {
                vendor?: ("greenhouse" | "ashby" | "lever") | null;
                include_removed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompaniesListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_company_api_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyAddBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_add_companies_api_companies_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompaniesBulkBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkInsertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_companies_api_companies_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_company_api_companies__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    insights_overview_api_insights_overview_get: {
        parameters: {
            query?: {
                window?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                tab?: "queue" | "pending_jd" | "all" | "scored" | "shortlisted" | "archived";
                statuses?: string[] | null;
                search?: string | null;
                posted_within_days?: number | null;
                require_verdict?: boolean;
                apply_hard_filters?: boolean;
                dedupe?: boolean;
                sort?: "discovered_desc" | "posted_desc" | "score_desc" | "company_asc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_transition_api_jobs_bulk_transition_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTransitionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_detail_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_to_job_api_jobs__job_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_apply_to_job_api_jobs__job_id__apply_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_followup_api_jobs__job_id__followup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowupBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interviews_api_jobs__job_id__interviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_interview_api_jobs__job_id__interviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewAddBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewRoundDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_interview_api_jobs__job_id__interviews__round_index__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
                round_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewCompleteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewRoundDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paste_jd_api_jobs__job_id__jd_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JdPasteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JdPasteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_note_api_jobs__job_id__note_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_job_api_jobs__job_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_job_api_jobs__job_id__transition_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    funnel_api_performance_funnel_get: {
        parameters: {
            query?: {
                window?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunnelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_stats_api_performance_llm_stats_get: {
        parameters: {
            query?: {
                window?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    performance_overview_api_performance_overview_get: {
        parameters: {
            query?: {
                window?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    step_timings_api_performance_step_timings_get: {
        parameters: {
            query?: {
                window?: number;
                step_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepTimingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_runs_api_runs_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    trigger_evaluate_api_runs_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerEvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_TriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_scan_api_runs_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_TriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_progress_api_runs__run_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
